<a href="https://colab.research.google.com/github/sayyidul/project_movie_analytics_myskill/blob/main/Project_Data_Preparation_for_Movie_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import pandas as pd # -> Module yang digunaakn untuk analisis data, editing dataframe
import numpy as np # -> Module yang digunakan untuk operasi matematika
import matplotlib.pyplot as plt # -> Module yang digunakan untuk melakukan visualisasi data
import seaborn as sns # -> Module yang digunakan untuk melakukan visualisasi data
import os # -> Untuk melakukan operasi sistem di google colab

In [ ]:
os.chdir("/content/gdrive/MyDrive/MySkill Project/Movie Analytics")

In [ ]:
os.listdir()

['movies_metadata.csv',
 'ratings_small.csv',
 'Mission_ Movie Analytics for Data Scientist.pptx',
 'Movie Analytics.ipynb']

In [ ]:
movies_data = pd.read_csv("movies_metadata.csv")

In [ ]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45463 entries, 0 to 45462
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  bool
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  int64
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  int64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  float64
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45463 non-null  bool
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: bool(2), float64(5), int64(2), object(15)
memory usage: 7.7+ MB

In [ ]:
movies_data.sample(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
6138,True,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,40718,tt0040946,en,Wake of the Red Witch,Captain Ralls fights Dutch shipping magnate Ma...,...,1948-12-30,0.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Romance! Adventure!...as wild as the RAGING SEAS!,Wake of the Red Witch,False,5.2,12.0
27501,True,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,205818,tt1839464,en,Eat,"After locking herself out of her apartment, a ...",...,2011-03-12,0.0,15.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Eat,False,8.0,1.0
21117,True,NaN,750000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.lionsgateshop.com/product.asp?Id=29...,201485,tt1698651,en,American Idiots,Four friends embark on a cross-country journey...,...,2013-06-18,0.0,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Get ready for the ultimate road trip,American Idiots,False,4.3,9.0
8379,True,"{'id': 438087, 'name': 'Topper Collection', 'p...",500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",NaN,23101,tt0029682,en,Topper,Madcap couple George and Marion Kerby are kill...,...,1937-07-16,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,90 ROARING MINUTES OF LAUGHS!,Topper,False,6.2,21.0
22676,True,"{'id': 293981, 'name': 'Flowers in the Attic C...",0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,236399,tt3074694,en,Flowers in the Attic,"After the sudden death of their father, four c...",...,2014-01-18,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Flowers in the Attic,False,6.3,106.0
40116,True,NaN,0,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",NaN,205361,tt0255851,en,Boycott,This made-for-TV movie dramatizes the historic...,...,2001-02-24,0.0,118.0,[],Released,The Story of Martin Luther King and One Act of...,Boycott,False,5.8,2.0
40704,True,NaN,500000,"[{'id': 53, 'name': 'Thriller'}]",NaN,416086,tt3907206,en,Redistributors,A city PR girl goes on the run accused of leak...,...,2016-07-02,0.0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Redistributors,False,5.1,6.0
29930,True,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,24632,tt0848552,en,The Mad,A horror-thriller in which a doctor and his te...,...,2007-05-22,0.0,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Mad,False,5.8,19.0
20283,True,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 37, 'nam...",NaN,52480,tt0061080,en,Texas Across the River,The Louisiana wedding of debutante Phoebe Ann ...,...,1966-10-26,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Swinging Fun-Romp that Fractures the Frontier!,Texas Across the River,False,5.7,5.0
5425,True,NaN,4800000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,26165,tt0270480,es,Juana la loca,The love story who transformed Juana I de Cast...,...,2001-09-28,0.0,115.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,NaN,Mad Love,False,5.2,6.0

In [ ]:
movies_data["release_date"] = pd.to_datetime(movies_data["release_date"])

In [ ]:
movies_data["release_date"].dtypes

dtype('<M8[ns]')

In [ ]:
movies_data["status"].unique()

array(['Released', nan, 'Rumored', 'Post Production', 'In Production',
       'Planned', 'Canceled'], dtype=object)

In [ ]:
movies_data["original_language"].nunique()

89

In [ ]:
english_release = movies_data[(movies_data["status"] == "Released") &\
                              (movies_data["original_language"] == "en")]

In [ ]:
english_release.sort_values(["budget","revenue"], ascending = [False, False]).head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
17124,True,"{'id': 295, 'name': 'Pirates of the Caribbean ...",380000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://disney.go.com/pirates/index-on-stranger...,1865,tt1298650,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,...,2011-05-14,1.045714e+09,136.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,False,6.4,5068.0
11827,True,"{'id': 295, 'name': 'Pirates of the Caribbean ...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://disney.go.com/disneypictures/pirates/,285,tt0449088,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",...,2007-05-19,9.610000e+08,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,False,6.9,4627.0
26557,True,"{'id': 86311, 'name': 'The Avengers Collection...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,...,2015-04-22,1.405404e+09,141.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A New Age Has Come.,Avengers: Age of Ultron,False,7.3,6908.0
11067,True,"{'id': 8537, 'name': 'Superman Collection', 'p...",270000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.superman.com,1452,tt0348150,en,Superman Returns,Superman returns to discover his 5-year absenc...,...,2006-06-28,3.910812e+08,154.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Superman Returns,False,5.4,1429.0
44839,True,"{'id': 8650, 'name': 'Transformers Collection'...",260000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,335988,tt3371366,en,Transformers: The Last Knight,"Autobots and Decepticons are at war, with huma...",...,2017-06-21,6.049421e+08,149.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For one world to live, the other must die.",Transformers: The Last Knight,False,6.2,1440.0
16130,True,"{'id': 463959, 'name': 'Tangled Collection', '...",260000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://disney.go.com/disneypictures/tangled/,38757,tt0398286,en,Tangled,When the kingdom's most wanted-and most charmi...,...,2010-11-24,5.917949e+08,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're taking adventure to new lengths.,Tangled,False,7.4,3419.0
18685,True,NaN,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://movies.disney.com/john-carter,49529,tt0401729,en,John Carter,"John Carter is a war-weary, former military ca...",...,2012-03-07,2.841391e+08,132.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Lost in our world, found in another.",John Carter,False,6.1,2170.0
11780,True,"{'id': 556, 'name': 'Spider-Man Collection', '...",258000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",http://www.sonypictures.com/movies/spider-man3/,559,tt0413300,en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,...,2007-05-01,8.908716e+08,139.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The battle within.,Spider-Man 3,False,5.9,3687.0
21174,True,NaN,255000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://disney.go.com/the-lone-ranger/,57201,tt1210819,en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,...,2013-07-03,8.928991e+07,149.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never Take Off the Mask,The Lone Ranger,False,5.9,2361.0
43252,True,"{'id': 9485, 'name': 'The Fast and the Furious...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.fastandfurious.com/,337339,tt4630562,en,The Fate of the Furious,When a mysterious woman seduces Dom into the w...,...,2017-04-12,1.238765e+09,136.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Family no more,The Fate of the Furious,False,6.8,3803.0

In [ ]:
english_release[english_release.duplicated(subset = "original_title", keep = False)].sort_values("original_title")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
15200,True,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,12219,tt0118528,en,12 Angry Men,During the trial of a man accused of his fathe...,...,1997-08-17,0.0,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,12 Angry Men,False,7.5,59.0
1161,True,NaN,350000,"[{'id': 18, 'name': 'Drama'}]",NaN,389,tt0050083,en,12 Angry Men,The defense and the prosecution have rested an...,...,1957-03-25,1000000.0,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Life is in their hands. Death is on their minds.,12 Angry Men,False,8.2,2130.0
20847,True,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,2966,tt0118248,en,"20,000 Leagues Under the Sea","The year is 1886, when New England's fishing h...",...,1997-05-11,0.0,158.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to the last place on earth.,"20,000 Leagues Under the Sea",False,4.6,13.0
13003,True,NaN,200000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,30266,tt0006333,en,"20,000 Leagues Under the Sea",Captain Nemo has built a fantastic submarine f...,...,1916-12-24,8000000.0,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The First Submarine Photoplay Ever Filmed,"20,000 Leagues Under the Sea",False,6.0,7.0
24108,True,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,2965,tt0118247,en,"20,000 Leagues Under the Sea","In the 19th century, an expert marine biologis...",...,1997-03-23,0.0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Darkness is to be feared... above and below.,"20,000 Leagues Under the Sea",False,6.3,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11646,True,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,1949,tt0443706,en,Zodiac,The true story of the investigation of 'The Zo...,...,2007-03-02,84785914.0,157.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,There's more than one way to lose your life to...,Zodiac,False,7.3,2080.0
37896,True,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,351065,tt3763866,en,Zoom,A multi-dimensional interface between a comic ...,...,2015-09-11,0.0,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Zoom,False,5.7,25.0
11171,True,NaN,35000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",NaN,14113,tt0383060,en,Zoom,Jack Shepard is an out-of-shape auto shop owne...,...,2006-08-11,12506188.0,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're going to save the world... as long as ...,Zoom,False,4.9,140.0
5761,True,"{'id': 374386, 'name': 'Anglo-Zulu War Collect...",3500000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,14433,tt0058777,en,Zulu,"In 1879, during the Zulu wars, man of the peop...",...,1964-01-22,8000000.0,138.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Dwarfing the mightiest! Towering over the grea...,Zulu,False,7.4,137.0
24662,True,NaN,16000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,185567,tt2249221,en,Zulu,"As a child, Ali Neuman narrowly escaped being ...",...,2013-12-04,0.0,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Zulu,False,6.7,176.0

In [ ]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45463 entries, 0 to 45462
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  bool
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  int64
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  int64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  float64
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  datetime64[ns]
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45463 non-null  bool
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(5), int64(2), object(14)
memory usage: 7.7+ MB

In [ ]:
movies_data.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,True,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,True,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,True,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,True,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,True,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
english_release.drop_duplicates(inplace = True)

/tmp/ipykernel_4662/4269851261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release.drop_duplicates(inplace = True)

In [ ]:
english_release["tagline"]= english_release["tagline"].fillna("No Tagline")

/tmp/ipykernel_4662/3117130801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release["tagline"]= english_release["tagline"].fillna("No Tagline")

In [ ]:
english_release["belongs_to_collection"] = english_release["belongs_to_collection"].fillna("No Data")
english_release["homepage"] = english_release["homepage"].fillna("No Data")
english_release['poster_path'] = english_release['poster_path'].fillna("No Data")

/tmp/ipykernel_4662/2744347569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release["belongs_to_collection"] = english_release["belongs_to_collection"].fillna("No Data")
/tmp/ipykernel_4662/2744347569.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release["homepage"] = english_release["homepage"].fillna("No Data")
/tmp/ipykernel_4662/2744347569.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release['poster_path'] = english_release['poster_path'].fillna("No Data")

In [ ]:
english_release.dropna(inplace=True)

/tmp/ipykernel_4662/2568499517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  english_release.dropna(inplace=True)

In [ ]:
english_release.shape

(31813, 24)

In [ ]:
english_release.sort_values("vote_count", ascending=False).head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
15480,True,No Data,160000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",...,2010-07-14,8.255328e+08,148.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your mind is the scene of the crime.,Inception,False,8.1,14075.0
12481,True,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,2008-07-16,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0
14551,True,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",...,2009-12-10,2.787965e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,False,7.2,12114.0
17818,True,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,...,2012-04-25,1.519558e+09,143.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some assembly required.,The Avengers,False,7.4,12000.0
26563,True,"{'id': 448150, 'name': 'Deadpool Collection', ...",58000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.foxmovies.com/movies/deadpool,293660,tt1431045,en,Deadpool,Deadpool tells the origin story of former Spec...,...,2016-02-09,7.831130e+08,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Witness the beginning of a happy ending,Deadpool,False,7.4,11444.0
22878,True,No Data,165000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",http://www.interstellarmovie.net/,157336,tt0816692,en,Interstellar,Interstellar chronicles the adventures of a gr...,...,2014-11-05,6.751200e+08,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,False,8.1,11187.0
20050,True,No Data,100000000,"[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name...",http://unchainedmovie.com/,68718,tt1853728,en,Django Unchained,"With the help of a German bounty hunter, a fre...",...,2012-12-25,4.253682e+08,165.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"Life, liberty and the pursuit of vengeance.",Django Unchained,False,7.8,10297.0
23752,True,"{'id': 284433, 'name': 'Guardians of the Galax...",170000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://marvel.com/guardians,118340,tt2015381,en,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",...,2014-07-30,7.733286e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,All heroes start somewhere.,Guardians of the Galaxy,False,7.9,10014.0
2843,True,No Data,63000000,"[{'id': 18, 'name': 'Drama'}]",http://www.foxmovies.com/movies/fight-club,550,tt0137523,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,...,1999-10-15,1.008538e+08,139.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Mischief. Mayhem. Soap.,Fight Club,False,8.3,9678.0
18244,True,"{'id': 131635, 'name': 'The Hunger Games Colle...",75000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.thehungergames.movie/,70160,tt1392170,en,The Hunger Games,Every year in the ruins of what was once North...,...,2012-03-12,6.912107e+08,142.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,May The Odds Be Ever In Your Favor.,The Hunger Games,False,6.9,9634.0

In [ ]:
english_release[english_release["runtime"] > 60 * 3]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
13,True,No Data,44000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",No Data,10858,tt0113987,en,Nixon,An all-star cast powers this epic look at Amer...,...,1995-12-22,13681765.0,192.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",Nixon,False,7.1,72.0
378,True,No Data,63000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",No Data,12160,tt0111756,en,Wyatt Earp,Covering the life and times of one of the West...,...,1994-06-24,25052000.0,191.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The epic story of love and adventure in a lawl...,Wyatt Earp,False,6.5,203.0
522,True,No Data,22000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",http://www.schindlerslist.com/,424,tt0108052,en,Schindler's List,The true story of how businessman Oskar Schind...,...,1993-11-29,321365567.0,195.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,"Whoever saves one life, saves the world entire.",Schindler's List,False,8.3,4436.0
530,True,No Data,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",No Data,695,tt0108122,en,Short Cuts,"Multi-storied, fish-eyed look at American cult...",...,1993-09-05,6110979.0,187.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Short Cuts raises the roof on America.,Short Cuts,False,6.9,136.0
583,True,No Data,22000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",No Data,581,tt0099348,en,Dances with Wolves,"Wounded Civil War soldier, John Dunbar tries t...",...,1990-11-09,424208848.0,181.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Inside everyone is a frontier waiting to be di...,Dances with Wolves,False,7.6,1084.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44755,True,No Data,0,[],No Data,128733,tt0080230,en,Hollywood,The definitive documentary about the American ...,...,1980-02-09,0.0,780.0,[],Released,No Tagline,Hollywood,False,8.0,1.0
44760,True,No Data,0,"[{'id': 99, 'name': 'Documentary'}]",No Data,461805,tt6840134,en,The Putin Interviews,"Academy Award-winning filmmaker, Oliver Stone ...",...,2017-06-12,0.0,240.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Know Your Enemy,The Putin Interviews,False,8.1,8.0
44924,True,No Data,0,"[{'id': 10752, 'name': 'War'}, {'id': 99, 'nam...",https://www.netflix.com/title/80049928,449758,tt6587094,en,Five Came Back,The extraordinary story of how Hollywood chang...,...,2017-03-31,0.0,195.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They Showed The War To The World,Five Came Back,False,8.3,8.0
44959,True,No Data,0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",No Data,32228,tt0386907,en,5ive Days to Midnight,A physicist discovers a briefcase containing p...,...,2004-01-01,0.0,210.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,No Tagline,5ive Days to Midnight,False,6.8,18.0
44992,True,"{'id': 2704, 'name': 'The Bible Collection', '...",20000000,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",No Data,2331,tt0199232,en,Jesus,The film is notable for presenting a more huma...,...,1999-12-25,0.0,240.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No Tagline,Jesus,False,5.4,8.0